### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by q3e** [simplewebrtc/simplewebrtc-demo-app#3] opened 2019-12-18 04:56 UTC
![swebrtc_not_working](https://user-images.githubusercontent.com/12845124/71056878-da8b4900-216b-11ea-9803-35d3868c22e2.png)

**Comment by eltel** [comment] 2020-01-12 19:29
Here neither...not a good look

**Comment by novotnej** [comment] 2020-03-18 14:12
Installed as per instructions, this is what I get

![image](https://user-images.githubusercontent.com/3701992/76969630-89cdec80-6922-11ea-8abb-52766f272470.png)

**Comment by jonoirwinrsa** [comment] 2020-03-25 15:50
Yeah I get the same as @novotnej :(

**Comment by madewulf** [comment] 2020-03-28 07:22
Same

**Comment by jugglingcats** [comment] 2020-04-03 15:50
Same as @novotnej

**Comment by one000mph** [comment] 2020-04-23 22:58
Hello there! This issue was caused by a React version issue and is now resolved by 9ff82bdae560b7771d9cc222e4bae2d7c2f3f82e. This repo is an older demo so for the latest demo of simplewebrtc please head over to  https://github.com/simplewebrtc/simplewebrtc-talky-sample-app.

Thanks for checking out our code

**Closed by one000mph** 2020-04-23 22:58 UTC
